master: 
  host: localhost
  port: 3306
  username: misope0600
  password: misope0700
  database: misopetr9708_godomall_com
slave1:
  host: localhost
  port: 3306
  username: misope0600
  password: misope0700
  database: misopetr9708_godomall_com
