master: 
  host: promalldb23.godomall.com
  port: 3306
  username: meatstudio
  password: meat014356
  database: meatstudio2_godomall_com
slave1:
  host: promalldb23.godomall.com
  port: 3306
  username: meatstudio
  password: meat014356
  database: meatstudio2_godomall_com
